name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: git init
    - name: clone
      run: git clone https://github.com/Shane-Xue/trials
    - name: build
      run: g++ salary.cpp -S
